version: '3.8'

services:

  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=example
    networks:
      - spring-postgres

  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    #    secrets:
    #      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=db-wrz2z
    #      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432

volumes:
  db-data:

#secrets:
#  db-password:
#    file: db/password.txt

networks:
  spring-postgres:
