### Check app health status
GET http://localhost:8080/actuator/health

### Show metrics (names)
GET http://localhost:8080/actuator/metrics/jvm.gc.pause

### List films
GET http://localhost:8080/films

### Get first film
GET http://localhost:8080/films/1

### Add a film
POST http://localhost:8080/films
Content-Type: application/json

{
  "id": 501,
  "title": "Jurassic World: Fallen Kingdom ",
  "description": "Действие фильма в начале происходит в 2016 году, а основные события — в 2018.",
  "year": 2019,
  "languageId": 1,
  "length": 128
}

### Other film searches
GET http://localhost:8080/films/search

### Search films by year
GET http://localhost:8080/films/search/findByYear?year=2019

### Get first three films, sorted by title
GET http://localhost:8080/films?page=0&size=3&sort=title,asc


### Profile example
GET http://localhost:8080/profile/actors