version: '3.8'

services:
  webapi:
    build:
      context: ./
      dockerfile: Dockerfile #Build.dockerfile
    image: webapi
    ports:
      - "8080:8080"
    networks:
      - network1

networks:
  network1: