version: '3'

services:

  postgres:
    image: kartoza/postgis   # postgis/postgis
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    container_name: postgis
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DBNAME: gis
      ALLOW_IP_RANGE: 0.0.0.0/0
    ports:
      - 5432:5432
    # networks:
    #   - psql_net
    volumes:
      - gis_db:/var/lib/postgresql/data
      # - ./data/dvdrental.sql:/docker-entrypoint-initdb.d/01_dvdrental.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  gis_db:
    driver: local   
    