version: '3.7'

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - 5432:5432
    networks:
      - psql_net
    volumes:
      - psql_db:/var/lib/postgresql/data
      # - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      # - ./data/data.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      # PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      # PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      # PGADMIN_LISTEN_PORT: 80
    ports:
      - 8088:80
    networks:
      - psql_net
    volumes:
      - pgadmin:/var/lib/pgadmin

networks:
  psql_net:
    driver: bridge

volumes:
  psql_db:
    driver: local
  pgadmin:
